name: Build and Push Backend Container

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/github-campus-club-psgct/kriya-26-backend:latest

      - name: Trigger Jenkins Deploy
        run: |
          curl -k -X POST "https://jendc.psgtech.ac.in/generic-webhook-trigger/invoke?token=kriya2026backend"